name = "PeriodicGraphs"
uuid = "18c5b727-b240-4874-878a-f2e242435bab"
authors = ["Lionel Zoubritzky lionel.zoubritzky@gmail.com"]
version = "0.10.4"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Graphs = "1.3"
PrecompileTools = "1"
StaticArrays = "0.12, 1.0"
julia = "1.6"

[workspace]
projects = ["test", "docs"]
