[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
PeriodicGraphs = "18c5b727-b240-4874-878a-f2e242435bab"

[compat]
Documenter = "1.0"
Literate = "2.0"
Graphs = "1.3"

[sources.PeriodicGraphs]
path = ".."
